[project]
name = "counterpoint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matteo", email = "matteo@giskard.ai" }
]
requires-python = ">=3.12.3"
dependencies = [
    "litellm>=1.72.2",
    "pydantic>=2.11.5",
    "pytest-asyncio>=1.0.0",
    "griffe>=0.27.0",
    "typing-extensions>=4.9.0",
    "jinja2>=3.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pylint-pydantic>=0.3.5",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
