name: Full CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre_checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6

      - name: Setup development environment
        run: make setup

      - name: Run all checks
        run: make check

  test:
    runs-on: ubuntu-latest
    env:
      TEST_MODEL: "gemini/gemini-2.0-flash"
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup development environment
        run: make setup

      - name: Run tests
        run: make test

  downstream-tests:
    runs-on: ubuntu-latest
    needs: [pre_checks, test]
    env:
      TEST_MODEL: "gemini/gemini-2.0-flash"
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - pkg: lidar
            ssh_secret: LIDAR_KEY
    steps:
      - name: Checkout counterpoint code
        uses: actions/checkout@v4
        with:
          path: counterpoint

      - name: Setup SSH
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.RELAIS_KEY }}
            ${{ secrets[matrix.ssh_secret] }}

      - name: Clone downstream package
        run: |
          git clone git@github.com:Giskard-AI/${{ matrix.pkg }}.git ${{ matrix.pkg }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build counterpoint wheel
        working-directory: counterpoint
        run: |
          uv build

      - name: Setup downstream package environment
        working-directory: ${{ matrix.pkg }}
        run: |
          # Update pyproject.toml to use local counterpoint build
          if [ -f pyproject.toml ]; then
            # Copy wheel to current directory with proper name
            WHEEL_PATH=$(ls ../counterpoint/dist/*.whl | head -1)
            WHEEL_NAME=$(basename "$WHEEL_PATH")
            cp "$WHEEL_PATH" "./$WHEEL_NAME"
            
            # Show current pyproject.toml for debugging
            echo "=== Original pyproject.toml [tool.uv.sources] section ==="
            grep -A 10 "\[tool\.uv\.sources\]" pyproject.toml || echo "No [tool.uv.sources] section found"
            
            # Remove existing [tool.uv.sources] section if it exists
            if grep -q "\[tool\.uv\.sources\]" pyproject.toml; then
              # Remove the entire [tool.uv.sources] section
              sed -i.bak '/\[tool\.uv\.sources\]/,/^\[/{ /^\[tool\.uv\.sources\]/d; /^\[/!d; }' pyproject.toml
            fi
            
            # Add new [tool.uv.sources] section with local source
            echo "" >> pyproject.toml
            echo "[tool.uv.sources]" >> pyproject.toml
            echo "counterpoint = { path = \"../counterpoint\", editable = true }" >> pyproject.toml
            
            # Show updated pyproject.toml for debugging
            echo "=== Updated pyproject.toml [tool.uv.sources] section ==="
            grep -A 10 "\[tool\.uv\.sources\]" pyproject.toml
          fi

          # Remove existing lock file to force fresh resolution
          rm -f uv.lock

          # Clear uv cache to ensure fresh resolution
          uv cache clean

          # Debug: Show what's in the counterpoint pyproject.toml
          echo "=== Counterpoint dependencies ==="
          grep -A 10 "dependencies" ../counterpoint/pyproject.toml

          # Install dependencies with lock file regeneration to resolve conflicts
          uv sync --all-extras --upgrade --resolution highest || {
            echo "=== Standard sync failed, trying alternative approach ==="
            # If that fails, try installing counterpoint without its dependencies first
            echo "counterpoint = { path = \"../counterpoint\", editable = true, extras = [] }" > temp_sources.toml
            mv temp_sources.toml temp_pyproject_addition.txt
            # Remove counterpoint from dependencies temporarily and add it back later
            uv add --editable ../counterpoint --no-sync
            uv sync --all-extras --upgrade --resolution highest
          }

      - name: Run downstream tests
        working-directory: ${{ matrix.pkg }}
        run: |
          # Run all tests
          if [ -f Makefile ] && grep -q "^test:" Makefile; then
            make test
          else
            uv run pytest tests/ --maxfail=5
          fi
