name: License Compliance (disabled in favor of Makefile targets)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use 'make licenses' and 'make licenses-check' locally."
