name: Tag and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: read

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from pyproject.toml
        id: get_version
        run: |
          VERSION_NUMBER=$(grep '^version\s*=' pyproject.toml | head -1 | cut -d '"' -f2)
          VERSION_NAME="v${VERSION_NUMBER}"
          printf 'version_number=%s\n' "$VERSION_NUMBER" >> "$GITHUB_OUTPUT"
          printf 'version_name=%s\n' "$VERSION_NAME" >> "$GITHUB_OUTPUT"

      - name: Check if tag exists
        env:
          VERSION_NAME: ${{ steps.get_version.outputs.version_name }}
        run: |
          if git rev-parse "refs/tags/$VERSION_NAME" >/dev/null 2>&1; then
            echo "Tag $VERSION_NAME already exists. Skipping."
            exit 0
          fi

      - name: Configure git
        run: |
          git config --global user.name 'BotReleaser'
          git config --global user.email 'bot.releaser@users.noreply.github.com'

      - name: Create and push tag
        env:
          VERSION_NAME: ${{ steps.get_version.outputs.version_name }}
        run: |
          git tag "$VERSION_NAME"
          git push origin "$VERSION_NAME"

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6

      - name: Install dependencies
        run: uv sync --frozen --all-extras --dev

      - name: Build package
        run: uv build

      - name: Create GitHub Release
        env:
          VERSION_NAME: ${{ steps.get_version.outputs.version_name }}
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5 # v2
        with:
          tag_name: ${{ env.VERSION_NAME }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            dist/*.tar.gz
            dist/*.whl
